### ISSUE TITLE
Could not load Newtonsoft.Json assembly

### ISSUE THREAD

**Issue by rokadias** [filipw/dotnet-script#129]
I'm using .Net Core 1.1.4: https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1.4-download.md

I downloaded 0.13 of `dotnet-script` and I can't seem to figure out why I'm getting the error below. I've tried including a different nuget reference of `#r "nuget:Newtonsoft.Json, 10.0.0"`.
```
Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
   at Auth0.ManagementApi.Clients.ConnectionsClient.GetAllAsync(String strategy, String fields, Boolean includeFields, String name)
   at Submission#0.<<Initialize>>d__0.MoveNext() in /Users/saqibrokadia/invio/scripts/auth0/auth/helloworld.csx:line 9
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
```

I think this has to do with dependency resolution of nuget, but feels like I'm pretty stuck here and not sure what else to try. I've read through other issues in this repository, but nothing seems to fix this.
```
#! "netcoreapp1.0"
#r "~/.nuget/packages/Newtonsoft.Json/10.0.3/lib/netstandard1.0/Newtonsoft.Json.dll"
#r "nuget:Auth0.ManagementApi, 4.4.0"

using Auth0.ManagementApi;

var client = new ManagementApiClient("token", new Uri("https://foo.auth0.com/api/v2/"));

Console.WriteLine(await client.Connections.GetAllAsync("auth0"));
```

**Comment by seesharper** [comment]
The following should be working in 0.14.0 when we get that out 
```
#r "nuget:Newtonsoft.Json, 10.0.2"
#r "nuget:Auth0.ManagementApi,4.4.0"
using Newtonsoft.Json;
using Auth0.ManagementApi;

var client = new ManagementApiClient("token", new Uri("https://foo.auth0.com/api/v2/"));

Console.WriteLine(await client.Connections.GetAllAsync("auth0"));
```
