### ISSUE TITLE
"eval" does not add NuGet packages to the project file

### ISSUE THREAD

**Issue by seesharper** [filipw/dotnet-script#203]
```
dotnet script -d eval '#r \"nuget:AutoMapper, 9.1.0\"; Console.WriteLine(typeof(MapperConfiguration));'
```

We should see a project file containing the package reference here 

```
Current runtime is 'win'.
Creating project file for *.csx files found in C:\repldemo using netcoreapp2.0 as the default framework.
Project file saved to C:\Users\bri\AppData\Local\Temp\scripts\C\repldemo\script.csproj
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup></ItemGroup>
</Project>
2.1.2
Restoring C:\Users\bri\AppData\Local\Temp\scripts\C\repldemo\script.csproj using the dotnet cli.
  Restore completed in 16,86 ms for C:\Users\bri\AppData\Local\Temp\scripts\C\repldemo\script.csproj.
Reading dependency context from C:\Users\bri\AppData\Local\Temp\scripts\C\repldemo\script.csproj
Resolved NuGet package folders: C:\Users\bri\.nuget\packages\;C:\Program Files\dotnet\sdk\NuGetFallbackFolder
Adding reference to an inherited dependency => Microsoft.CodeAnalysis
Adding reference to an inherited dependency => Microsoft.CodeAnalysis.CSharp
Adding reference to an inherited dependency => Microsoft.CodeAnalysis.CSharp.Scripting
Adding reference to an inherited dependency => Microsoft.CodeAnalysis.Scripting
(1,29): error CS1025: Single-line comment or end-of-line expected
Microsoft.CodeAnalysis.Scripting.CompilationErrorException: Script compilation failed due to one or more errors.
   at Dotnet.Script.Core.ScriptCompiler.CreateCompilationContext[TReturn,THost](ScriptContext context) in C:\Github\fresh\dotnet-script\src\Dotnet.Script.Core\ScriptCompiler.cs:line 151
   at Dotnet.Script.Core.ScriptRunner.Execute[TReturn,THost](ScriptContext context, THost host) in C:\Github\fresh\dotnet-script\src\Dotnet.Script.Core\ScriptRunner.cs:line 32
   at Dotnet.Script.Program.<>c__DisplayClass3_0.<<Wain>b__3>d.MoveNext() in C:\Github\fresh\dotnet-script\src\Dotnet.Script\Program.cs:line 72
```

**Comment by filipw** [comment]
The bug here is that `#r` and `#load` as preprocessor directives can only have comments on the same line, that's part of C# spec.
Probably the easiest fix would be to parse the code into an AST before execution and inject a new line after each preprocess directive.

**Comment by seesharper** [comment]
I see 👍  
Another thing I tried was to pipe into REPL mode like this 

```
echo 'Console.WriteLine(42)' | dotnet script
```

Then `dotnet script` seems to get stuck in a loop 

```
> 42
> > > > > > > ^CTerminate batch job (Y/N)?
```

I don't know if that should even be possible to do ? 😄

**Comment by filipw** [comment]
> Probably the easiest fix would be to parse the code into an AST before execution and inject a new line after each preprocess directive.

which on second thought is not so easy because it is a chicken and egg problem. Roslyn AST will not be able to determine where the preprocessor directive ends *without* a new line 😀

**Comment by wk-j** [comment]
@seesharper  It show difference output on Mac OS

```bash
❯ dotnet script -d eval '#r "nuget:AutoMapper, 9.1.0"; Console.WriteLine(typeof(MapperConfiguration));'
Current runtime is 'osx'.
Project file saved to /var/folders/1f/gvql81l17dn23gc9m2b64nk00000gn/T/scripts/Users/wk/Source/github/DotNetEval/REPL/script.csproj
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="9.1.0" />
  </ItemGroup>
</Project>
2.1.2
Restoring /var/folders/1f/gvql81l17dn23gc9m2b64nk00000gn/T/scripts/Users/wk/Source/github/DotNetEval/REPL/script.csproj using the dotnet cli.
  Restoring packages for /var/folders/1f/gvql81l17dn23gc9m2b64nk00000gn/T/scripts/Users/wk/Source/github/DotNetEval/REPL/script.csproj...
/var/folders/1f/gvql81l17dn23gc9m2b64nk00000gn/T/scripts/Users/wk/Source/github/DotNetEval/REPL/script.csproj : error NU1102: Unable to find package AutoMapper with version (>= 9.1.0)
/var/folders/1f/gvql81l17dn23gc9m2b64nk00000gn/T/scripts/Users/wk/Source/github/DotNetEval/REPL/script.csproj : error NU1102:   - Found 207 version(s) in nuget.org [ Nearest version: 6.2.2 ]
  Generating MSBuild file /private/var/folders/1f/gvql81l17dn23gc9m2b64nk00000gn/T/scripts/Users/wk/Source/github/DotNetEval/REPL/obj/script.csproj.nuget.g.props.
  Restore failed in 1.8 sec for /var/folders/1f/gvql81l17dn23gc9m2b64nk00000gn/T/scripts/Users/wk/Source/github/DotNetEval/REPL/script.csproj.
System.Exception: Unable to restore packages from '/var/folders/1f/gvql81l17dn23gc9m2b64nk00000gn/T/scripts/Users/wk/Source/github/DotNetEval/REPL/script.csproj'. Make sure that all script files contains valid NuGet references
   at Dotnet.Script.DependencyModel.Context.DotnetRestorer.Restore(String pathToProjectFile) in X:\Documents\dev\dotnet-script\src\Dotnet.Script.DependencyModel\Context\DotnetRestorer.cs:line 25
   at Dotnet.Script.DependencyModel.Context.ScriptDependencyInfoProvider.GetDependencyInfo(String pathToProjectFile) in X:\Documents\dev\dotnet-script\src\Dotnet.Script.DependencyModel\Context\ScriptDependencyInfoProvider.cs:line 33
   at Dotnet.Script.DependencyModel.Runtime.RuntimeDependencyResolver.GetDependenciesInternal(String pathToProjectFile) in X:\Documents\dev\dotnet-script\src\Dotnet.Script.DependencyModel\Runtime\RuntimeDependencyResolver.cs:line 62
   at Dotnet.Script.Core.ScriptCompiler.CreateCompilationContext[TReturn,THost](ScriptContext context) in X:\Documents\dev\dotnet-script\src\Dotnet.Script.Core\ScriptCompiler.cs:line 97
   at Dotnet.Script.Core.ScriptRunner.Execute[TReturn,THost](ScriptContext context, THost host) in X:\Documents\dev\dotnet-script\src\Dotnet.Script.Core\ScriptRunner.cs:line 35
   at Dotnet.Script.Program.<>c__DisplayClass3_0.<<Wain>b__3>d.MoveNext() in X:\Documents\dev\dotnet-script\src\Dotnet.Script\Program.cs:line 79
```

If I change version of AutoMapper It show another error message like this

```bash
❯ dotnet script -d eval '#r "nuget:AutoMapper, 6.2.2"; Console.WriteLine(typeof(MapperConfiguration));'
Current runtime is 'osx'.
Project file saved to /var/folders/1f/gvql81l17dn23gc9m2b64nk00000gn/T/scripts/Users/wk/Source/github/DotNetEval/REPL/script.csproj
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="6.2.2" />
  </ItemGroup>
</Project>
2.1.2
Restoring /var/folders/1f/gvql81l17dn23gc9m2b64nk00000gn/T/scripts/Users/wk/Source/github/DotNetEval/REPL/script.csproj using the dotnet cli.
  Restoring packages for /var/folders/1f/gvql81l17dn23gc9m2b64nk00000gn/T/scripts/Users/wk/Source/github/DotNetEval/REPL/script.csproj...
  Installing AutoMapper 6.2.2.
  Generating MSBuild file /private/var/folders/1f/gvql81l17dn23gc9m2b64nk00000gn/T/scripts/Users/wk/Source/github/DotNetEval/REPL/obj/script.csproj.nuget.g.props.
  Restore completed in 2.49 sec for /var/folders/1f/gvql81l17dn23gc9m2b64nk00000gn/T/scripts/Users/wk/Source/github/DotNetEval/REPL/script.csproj.
Reading dependency context from /var/folders/1f/gvql81l17dn23gc9m2b64nk00000gn/T/scripts/Users/wk/Source/github/DotNetEval/REPL/script.csproj
Resolved NuGet package folders: /Users/wk/.nuget/packages/;/usr/local/share/dotnet/sdk/NuGetFallbackFolder
Resolved runtime library AutoMapper located at /Users/wk/.nuget/packages/automapper/6.2.2/lib/netstandard1.3/AutoMapper.dll
Resolved runtime library Microsoft.CSharp located at /Users/wk/.nuget/packages/microsoft.csharp/4.3.0/lib/netstandard1.3/Microsoft.CSharp.dll
Resolved runtime library System.Collections.Concurrent located at /Users/wk/.nuget/packages/system.collections.concurrent/4.3.0/lib/netstandard1.3/System.Collections.Concurrent.dll
Resolved runtime library System.Collections.NonGeneric located at /usr/local/share/dotnet/sdk/NuGetFallbackFolder/system.collections.nongeneric/4.3.0/lib/netstandard1.3/System.Collections.NonGeneric.dll
Resolved runtime library System.Collections.Specialized located at /usr/local/share/dotnet/sdk/NuGetFallbackFolder/system.collections.specialized/4.3.0/lib/netstandard1.3/System.Collections.Specialized.dll
Resolved runtime library System.ComponentModel located at /Users/wk/.nuget/packages/system.componentmodel/4.3.0/lib/netstandard1.3/System.ComponentModel.dll
Resolved runtime library System.ComponentModel.Primitives located at /usr/local/share/dotnet/sdk/NuGetFallbackFolder/system.componentmodel.primitives/4.3.0/lib/netstandard1.0/System.ComponentModel.Primitives.dll
Resolved runtime library System.ComponentModel.TypeConverter located at /usr/local/share/dotnet/sdk/NuGetFallbackFolder/system.componentmodel.typeconverter/4.3.0/lib/netstandard1.5/System.ComponentModel.TypeConverter.dll
Resolved runtime library System.Dynamic.Runtime located at /Users/wk/.nuget/packages/system.dynamic.runtime/4.3.0/lib/netstandard1.3/System.Dynamic.Runtime.dll
Resolved runtime library System.Linq located at /Users/wk/.nuget/packages/system.linq/4.3.0/lib/netstandard1.6/System.Linq.dll
Resolved runtime library System.Linq.Expressions located at /Users/wk/.nuget/packages/system.linq.expressions/4.3.0/lib/netstandard1.6/System.Linq.Expressions.dll
Resolved runtime library System.Linq.Queryable located at /Users/wk/.nuget/packages/system.linq.queryable/4.3.0/lib/netstandard1.3/System.Linq.Queryable.dll
Resolved runtime library System.ObjectModel located at /Users/wk/.nuget/packages/system.objectmodel/4.3.0/lib/netstandard1.3/System.ObjectModel.dll
Resolved runtime library System.Reflection.Emit located at /Users/wk/.nuget/packages/system.reflection.emit/4.3.0/lib/netstandard1.3/System.Reflection.Emit.dll
Resolved runtime library System.Reflection.Emit.ILGeneration located at /Users/wk/.nuget/packages/system.reflection.emit.ilgeneration/4.3.0/lib/netstandard1.3/System.Reflection.Emit.ILGeneration.dll
Resolved runtime library System.Reflection.Emit.Lightweight located at /Users/wk/.nuget/packages/system.reflection.emit.lightweight/4.3.0/lib/netstandard1.3/System.Reflection.Emit.Lightweight.dll
Resolved runtime library System.Reflection.TypeExtensions located at /Users/wk/.nuget/packages/system.reflection.typeextensions/4.3.0/lib/netstandard1.5/System.Reflection.TypeExtensions.dll
Resolved runtime library System.Runtime.Serialization.Primitives located at /usr/local/share/dotnet/sdk/NuGetFallbackFolder/system.runtime.serialization.primitives/4.3.0/lib/netstandard1.3/System.Runtime.Serialization.Primitives.dll
Resolved runtime library System.Text.RegularExpressions located at /Users/wk/.nuget/packages/system.text.regularexpressions/4.3.0/lib/netstandard1.6/System.Text.RegularExpressions.dll
Resolved runtime library System.Threading located at /Users/wk/.nuget/packages/system.threading/4.3.0/lib/netstandard1.3/System.Threading.dll
Adding reference to a runtime dependency => Name: AutoMapper, Version=6.2.2.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005, Path: /Users/wk/.nuget/packages/automapper/6.2.2/lib/netstandard1.3/AutoMapper.dll
Adding reference to a runtime dependency => Name: Microsoft.CSharp, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Path: /Users/wk/.nuget/packages/microsoft.csharp/4.3.0/lib/netstandard1.3/Microsoft.CSharp.dll
Adding reference to a runtime dependency => Name: System.Collections.Concurrent, Version=4.0.13.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Path: /Users/wk/.nuget/packages/system.collections.concurrent/4.3.0/lib/netstandard1.3/System.Collections.Concurrent.dll
Adding reference to a runtime dependency => Name: System.Collections.NonGeneric, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Path: /usr/local/share/dotnet/sdk/NuGetFallbackFolder/system.collections.nongeneric/4.3.0/lib/netstandard1.3/System.Collections.NonGeneric.dll
Adding reference to a runtime dependency => Name: System.Collections.Specialized, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Path: /usr/local/share/dotnet/sdk/NuGetFallbackFolder/system.collections.specialized/4.3.0/lib/netstandard1.3/System.Collections.Specialized.dll
Adding reference to a runtime dependency => Name: System.ComponentModel, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Path: /Users/wk/.nuget/packages/system.componentmodel/4.3.0/lib/netstandard1.3/System.ComponentModel.dll
Adding reference to a runtime dependency => Name: System.ComponentModel.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Path: /usr/local/share/dotnet/sdk/NuGetFallbackFolder/system.componentmodel.primitives/4.3.0/lib/netstandard1.0/System.ComponentModel.Primitives.dll
Adding reference to a runtime dependency => Name: System.ComponentModel.TypeConverter, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Path: /usr/local/share/dotnet/sdk/NuGetFallbackFolder/system.componentmodel.typeconverter/4.3.0/lib/netstandard1.5/System.ComponentModel.TypeConverter.dll
Adding reference to a runtime dependency => Name: System.Dynamic.Runtime, Version=4.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Path: /Users/wk/.nuget/packages/system.dynamic.runtime/4.3.0/lib/netstandard1.3/System.Dynamic.Runtime.dll
Adding reference to a runtime dependency => Name: System.Linq, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Path: /Users/wk/.nuget/packages/system.linq/4.3.0/lib/netstandard1.6/System.Linq.dll
Adding reference to a runtime dependency => Name: System.Linq.Expressions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Path: /Users/wk/.nuget/packages/system.linq.expressions/4.3.0/lib/netstandard1.6/System.Linq.Expressions.dll
Adding reference to a runtime dependency => Name: System.Linq.Queryable, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Path: /Users/wk/.nuget/packages/system.linq.queryable/4.3.0/lib/netstandard1.3/System.Linq.Queryable.dll
Adding reference to a runtime dependency => Name: System.ObjectModel, Version=4.0.13.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Path: /Users/wk/.nuget/packages/system.objectmodel/4.3.0/lib/netstandard1.3/System.ObjectModel.dll
Adding reference to a runtime dependency => Name: System.Reflection.Emit, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Path: /Users/wk/.nuget/packages/system.reflection.emit/4.3.0/lib/netstandard1.3/System.Reflection.Emit.dll
Adding reference to a runtime dependency => Name: System.Reflection.Emit.ILGeneration, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Path: /Users/wk/.nuget/packages/system.reflection.emit.ilgeneration/4.3.0/lib/netstandard1.3/System.Reflection.Emit.ILGeneration.dll
Adding reference to a runtime dependency => Name: System.Reflection.Emit.Lightweight, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Path: /Users/wk/.nuget/packages/system.reflection.emit.lightweight/4.3.0/lib/netstandard1.3/System.Reflection.Emit.Lightweight.dll
Adding reference to a runtime dependency => Name: System.Reflection.TypeExtensions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Path: /Users/wk/.nuget/packages/system.reflection.typeextensions/4.3.0/lib/netstandard1.5/System.Reflection.TypeExtensions.dll
Adding reference to a runtime dependency => Name: System.Runtime.Serialization.Primitives, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Path: /usr/local/share/dotnet/sdk/NuGetFallbackFolder/system.runtime.serialization.primitives/4.3.0/lib/netstandard1.3/System.Runtime.Serialization.Primitives.dll
Adding reference to a runtime dependency => Name: System.Text.RegularExpressions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Path: /Users/wk/.nuget/packages/system.text.regularexpressions/4.3.0/lib/netstandard1.6/System.Text.RegularExpressions.dll
Adding reference to a runtime dependency => Name: System.Threading, Version=4.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, Path: /Users/wk/.nuget/packages/system.threading/4.3.0/lib/netstandard1.3/System.Threading.dll
Adding reference to an inherited dependency => Microsoft.CodeAnalysis
Adding reference to an inherited dependency => Microsoft.CodeAnalysis.CSharp
Adding reference to an inherited dependency => Microsoft.CodeAnalysis.CSharp.Scripting
Adding reference to an inherited dependency => Microsoft.CodeAnalysis.Scripting
(1,29): error CS1025: Single-line comment or end-of-line expected
```
