### ISSUE TITLE
Windows build fails in build\Choco.csx on line 14

### ISSUE THREAD

**Issue by atifaziz** [filipw/dotnet-script#346]
I attempted to build the latest commit of `master`, which was d03a0267877af00099ee4ed872ee9888e35087e2 at the time of reporting this issue.

My working copy was in a clean state (`git clean --xdf`).

I ran `./build.ps1` but it failed with the following error:

```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'A:\dotnet-script\Chocolatey\tools\LICENSE.TXT'.
   at System.IO.Win32FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Submission#0.Choco.Pack(String pathToProjectFolder, String pathToBinaries, String outputFolder) in A:\dotnet-script\build\Choco.csx:line 14
   at Submission#0.<<Initialize>>d__0.MoveNext() in A:\dotnet-script\build\build.csx:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
```

It seems to have failed here:

https://github.com/filipw/dotnet-script/blob/b9fc6c1390b8fdf47c96750df3e12be674482229/build/Choco.csx#L14

I'm happy to provide the full build log if it helps.

I do not have [Chocolatey](https://chocolatey.org/) installed. Is it a requirement? I didn't find any build instructions.

Other than that, I was building on Microsoft Windows 10.0.17134.285.

**Comment by seesharper** [comment]
Yup. For know you'll need Chocolatey installed when building trough the build script. 

This should also work 

```
dotnet build -c release 
```

**Comment by atifaziz** [comment]
> Chocolatey installed when building trough the build script.

Had a hunch that'd be the case but thanks for confirming. I'll close this issue but perhaps worth adding that requirement as a note to README?
