### ISSUE TITLE
REPL fails in git bash in Windows

### ISSUE THREAD

**Issue by anwarnajim** [filipw/dotnet-script#406]
```
$ dotnet script --version
\0.28.0

$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.502
 Commit:    c74ce8f29f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.502\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8


$ sh --version
GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
Copyright (C) 2016 Free Software Foundation, Inc.


$ git --version
git version 2.20.1.windows.1
```

trying to run REPL always fail with:-
```
$ dotnet script
> Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
```

When running in debug mode:-
```
$ dotnet script -d
> System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
   at System.ConsolePal.ReadKey(Boolean intercept)
   at System.ReadLine.GetText(KeyHandler keyHandler)
   at System.ReadLine.Read(String prompt, String default)
   at Dotnet.Script.Core.InteractiveRunner.ReadInput() in C:\Users\appveyor\AppData\Local\Temp\tmp382F\Dotnet.Script.Core\Interactive\InteractiveRunner.cs:line 129
   at Dotnet.Script.Core.InteractiveRunner.RunLoop() in C:\Users\appveyor\AppData\Local\Temp\tmp382F\Dotnet.Script.Core\Interactive\InteractiveRunner.cs:line 47
   at Dotnet.Script.Core.Commands.ExecuteInteractiveCommand.Execute(ExecuteInteractiveCommandOptions options) in C:\Users\appveyor\AppData\Local\Temp\tmp382F\Dotnet.Script.Core\Commands\ExecuteInteractiveCommand.cs:line 26
   at Dotnet.Script.Program.RunInteractive(Boolean useRestoreCache, LogFactory logFactory, String[] packageSources) in C:\Users\appveyor\AppData\Local\Temp\tmp382F\Dotnet.Script\Program.cs:line 239
   at Dotnet.Script.Program.<>c__DisplayClass4_0.<<Wain>b__8>d.MoveNext() in C:\Users\appveyor\AppData\Local\Temp\tmp382F\Dotnet.Script\Program.cs:line 228
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
   at Dotnet.Script.Program.Main(String[] args) in C:\Users\appveyor\AppData\Local\Temp\tmp382F\Dotnet.Script\Program.cs:line 26
```

Working with no problem when running in cmd or powershell

**Comment by filipw** [comment]
I don't think Console.ReadKey in .NET Core works at all for redirected outputs
