### ISSUE TITLE
Conflict of Libraries from external package

### ISSUE THREAD

**Issue by chris-zioutas-cko** [filipw/dotnet-script#429]
Code gist: https://gist.github.com/chris-zioutas-cko/485eda641c28a93158ca9bb467cae376
Stacktrace: https://gist.github.com/chris-zioutas-cko/dd22a7e916d71e1fa8cc0595f5c40a98

It seems that there is a missmatch between the required library between the Seq.Api package and the runtime of the script.

This issue appears when the code tries to initialize a new connection object (SEQ).

It does not seem to affect windows but OSX

This was solved by downgrading the required packages `Microsoft.Extensions.Configuration.*` to 2.0.0

Major versions of .net core (sdk & runtime) are the same for both machines (windows & OSX)

**Comment by seesharper** [comment]
Hi @chris-zioutas-cko 

What version are you on?

Could you do a `dotnet script --info` and paste the result here?

FYI, I tried the following on 0.28.0 (OSX)

```
#!/usr/bin/env dotnet-script

#r "nuget: Seq.Api, 5.0.0"
#r "nuget: Microsoft.Extensions.Configuration, 2.1.0"
#r "nuget: Microsoft.Extensions.Configuration.FileExtensions, 2.1.0"
#r "nuget: Microsoft.Extensions.Configuration.Json, 2.1.0"
#r "nuget: Microsoft.Extensions.Configuration.Binder, 2.1.0"

using Seq.Api;
using Seq.Api.Client;
using Seq.Api.Model.Inputs;
using Seq.Api.Model.Signals;
using System;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Configuration.Binder;

public static class Program
{
    private static SeqConnection _seqConnection;

    /// <summary>
    /// Main script process entry method.
    /// </summary>
    /// <param name="Args">The Args string array passed through cmd</param>
    public static async Task Run(IList<string> Args)
    {
        _seqConnection = new SeqConnection("connection string");
        await _seqConnection.Users.LoginAsync("username", "password");
    }
}



// Args is a global variable injected to pass cmd arguments
await Program.Run(Args);
```

And the result 

```
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Seq.Api.Client.SeqApiClient..ctor(String serverUrl, String apiKey, Boolean useDefaultCredentials)
   at Seq.Api.SeqConnection..ctor(String serverUrl, String apiKey, Boolean useDefaultCredentials)
   at Submission#0.Program.Run(IList`1 Args) in /Users/bernhardrichter/GitHub/issue429/main.csx:line 31
   at Submission#0.<<Initialize>>d__0.MoveNext() in /Users/bernhardrichter/GitHub/issue429/main.csx:line 39
--- End of stack trace from previous location where exception was thrown ---
   at Dotnet.Script.Core.ScriptRunner.Execute[TReturn](String dllPath, IEnumerable`1 commandLineArgs) in C:\Users\appveyor\AppData\Local\Temp\tmp382F\Dotnet.Script.Core\ScriptRunner.cs:line 58
```

**Comment by chris-zioutas-cko** [comment]
hey @seesharper 
Thanks for the quick reply and sorry for my late reply.
After your msg we were looking at the versions and the OSX was running on 0.16.0 we fixed the version and everything is ok now.
