### ISSUE TITLE
System.IO.FileLoadException when trying to use Microsoft.Extensions.Configuration nuget package

### ISSUE THREAD

**Issue by gldraphael** [filipw/dotnet-script#435]
Stacktrace:

```
System.TypeInitializationException: The type initializer for 'Submission#0' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.Configuration, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621) ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.Configuration, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.AppDomain.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Submission#0.<<Initialize>>d__0.MoveNext() in /Users/gldraphael/projects/misc/vi/config.csx:line 16
--- End of stack trace from previous location where exception was thrown ---
   at Dotnet.Script.Core.ScriptRunner.Execute[TReturn](String dllPath, IEnumerable`1 commandLineArgs) in C:\Users\appveyor\AppData\Local\Temp\tmp382F\Dotnet.Script.Core\ScriptRunner.cs:line 58
```

Here's the `config.csx` file I'm trying to run:

```csharp
#!/usr/bin/env dotnet-script
#r "nuget: Microsoft.Extensions.Configuration, 2.2.0"
#r "nuget: Microsoft.Extensions.Configuration.FileExtensions, 2.2.0"
#r "nuget: Microsoft.Extensions.Configuration.Json, 2.2.0"
#r "nuget: Microsoft.Extensions.Configuration.Binder, 2.2.0"

using Microsoft.Extensions.Configuration;

public static var config = new ConfigurationBuilder()
          .AddJsonFile("config.json", optional: false, reloadOnChange: true)
          .AddJsonFile("config.secrets.json", optional: true, reloadOnChange: true)
          .Build()
          .Get<Config>();
Console.WriteLine(config.Secret); // works if I comment this out, but then what's the point

public class Config 
{
    public string Secret { get; set; }
}
```

---
```bash
$ dotnet script --info
Version             : 0.28.0
Install location    : /Users/gldraphael/.dotnet/tools/.store/dotnet-script/0.28.0/dotnet-script/0.28.0/tools/netcoreapp2.1/any
Target framework    : netcoreapp2.1
.NET Core version   : 2.1.5
Platform identifier : osx
Runtime identifier  : osx-x64
```

**Comment by filipw** [comment]
dotnet-script has indirect dependency on `Microsoft.Extensions.Configuration 2.1.1` which causes the issue, since that older version is already loaded into the runtime before you attempt to load yours from the script.

The most basic repro is:

(anything higher than 2.1.1 will break)

```
#r "nuget: Microsoft.Extensions.Configuration, 2.1.6"

using Microsoft.Extensions.Configuration;

var builder = typeof(ConfigurationBuilder);
Console.WriteLine(builder); 
``` 

We will try to come up with a fix, but for now, the recommended workaround is to use max. versions 2.1.1 of those config packages:

```
#!/usr/bin/env dotnet-script
#r "nuget: Microsoft.Extensions.Configuration, 2.1.1"
#r "nuget: Microsoft.Extensions.Configuration.FileExtensions, 2.1.1"
#r "nuget: Microsoft.Extensions.Configuration.Json, 2.1.1"
#r "nuget: Microsoft.Extensions.Configuration.Binder, 2.1.1"

using Microsoft.Extensions.Configuration;

public static var config = new ConfigurationBuilder()
          .AddJsonFile("config.json", optional: false, reloadOnChange: true)
          .AddJsonFile("config.secrets.json", optional: true, reloadOnChange: true)
          .Build()
          .Get<Config>();
Console.WriteLine(config.Secret); // works if I comment this out, but then what's the point

public class Config 
{
    public string Secret { get; set; }
}
```

**Comment by seesharper** [comment]
This is not by any means ideal. Part of the problem here is that the script execution shares the same `AssemblyLoadContext` with the host. A while back, I looked at providing a custom load context for script execution, but eventually gave up as there was no way to do this, even with reflection hacks. This might have changed since the last time I looked, though

**Comment by filipw** [comment]
> This might have changed since the last time I looked, though

this is still not possible, however, I mentioned this already to the Roslyn guys and it will definitely need to be changed - so that collectible assemblies are supported.

**Comment by mrtristan** [comment]
@filipw  are there by chance any tricks for getting past this issue? I'm in a rough spot in that i've got third party libs (in this case, the latest version of EPPlus) which have internal refs to `Microsoft.Extensions.Configuration, 2.2.0` so things are blowing up on me. I love your guys' tool here and want to keep using it for little one-off things i need to do here and there but it's painful having to fight little things like this. (i hear your pain though in fighting the roslyn capabilities you've got to work with).

**Comment by drosenba** [comment]
Any solution here yet?  I too am getting the same error when I use EPPlus.  
  System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.Configuration, Version=3.1.5.0, 

Happens when using only
#r "nuget: EPPlus, 5.3.2"

and also when adding
#r "nuget: Microsoft.Extensions.Configuration, 3.1.5"

(Works fine in LinqPad ;)
