### ISSUE TITLE
Accessing file from current directory works, but accessing configuration files do not

### ISSUE THREAD

**Issue by gldraphael** [filipw/dotnet-script#439]
**Stacktrace:**
```
System.TypeInitializationException: The type initializer for 'Submission#0' threw an exception. ---> System.IO.FileNotFoundException: The configuration file 'config.json' was not found and is not optional. The physical path is '/usr/local/lib/dotnet-script/config.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Submission#0..cctor() in /Users/gldraphael/projects/misc/vi/config.csx:line 9
   --- End of inner exception stack trace ---
   at Submission#0.<<Initialize>>d__0.MoveNext() in /Users/gldraphael/projects/misc/vi/config.csx:line 14
--- End of stack trace from previous location where exception was thrown ---
   at Dotnet.Script.Core.ScriptRunner.Execute[TReturn](String dllPath, IEnumerable`1 commandLineArgs) in C:\projects\dotnet-script\src\Dotnet.Script.Core\ScriptRunner.cs:line 58
```
**Source:**
```csharp
#!/usr/bin/env dotnet-script
#r "nuget: Microsoft.Extensions.Configuration.Json, 2.1.1"
#r "nuget: Microsoft.Extensions.Configuration.Binder, 2.1.1"
#load "serilog.csx"

using Microsoft.Extensions.Configuration;
using Serilog;

public static var config = new ConfigurationBuilder()
          .AddJsonFile("config.json", optional: false, reloadOnChange: true)
          .AddJsonFile("config.secrets.json", optional: true, reloadOnChange: true)
          .Build()
          .Get<Config>();
Log.Verbose(config.Secret);
public class Config { public string Secret { get; set; } }
```
File structure:
```text
~
  - config.csx
  - config.json
  - config.secrets.json
```

However, another script that accesses a file works just fine:
```csharp
#!/usr/bin/env dotnet-script
#r "nuget: SubtitlesParser, 1.4.7"
#load "serilog.csx"

using Serilog;
using SubtitlesParser.Classes.Parsers;

var parser = new VttParser();
using (var fileStream = File.OpenRead("captions.vtt"))
{
    var items = parser.ParseStream(fileStream, Encoding.UTF8);
    Log.Verbose("{@items}", items);
}
```

```text
~
  - parse.csx
  - captions.vtt
```

--- 

serilog.csx
```csharp
#!/usr/bin/env dotnet-script
#r "nuget: Serilog.Sinks.Console, 3.1.1"

using Serilog;

Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Verbose()
    .WriteTo.Console()
    .CreateLogger();
```

Possibly related: #435

**Comment by filipw** [comment]
@seesharper is this caused by us not resetting the current directory correctly? since the script runs from the temp folder

**Comment by seesharper** [comment]
This is related to how `Microsoft.Extensions.Logging` resolves the full path to the config file when you give it a relative path. My guess her is that it is resolved based on the executing assembly which is `dotnet-script`. 

There is really not much we can do about this other than providing the full path to the config file.

In this case like this

```
public static var config = new ConfigurationBuilder()
          .AddJsonFile(Path.GetFullPath("config.json"), optional: false, reloadOnChange: true)
          .Build()
          .Get<Config>();
```
