### ISSUE TITLE
publish command fails when script path has spaces

### ISSUE THREAD

**Issue by phxvyper** [filipw/dotnet-script#456]
System information:
```sh
λ dotnet --version
2.1.602
λ dotnet script --version
0.29.1
λ  systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.16299 N/A Build 16299
```

Replicating:
```sh
λ dotnet script new test.csx
Creating 'test.csx'
...'C:\Users\ashley\test script\test.csx' [Created]

λ dotnet script test.csx
Hello world!

λ dotnet script publish test.csx
dotnet publish failed with result '1'
```

**Comment by filipw** [comment]
can you please post the output of `dotnet script --debug publish main.csx`?

**Comment by phxvyper** [comment]
I was able to successfully publish the script when i moved it to a directory with no spaces.

This works:
```sh
λ mkdir ~/testscript && cd ~/testscript
λ dotnet script new test.csx
λ dotnet script publish test.csx
```

This does not work:
```sh
λ mkdir ~/test\ script && cd ~/test\ script
λ dotnet script new test.csx
λ dotnet script publish test.csx
```

Debug output:
```
λ dotnet script --debug publish test.csx
info: Dotnet.Script.Core.ScriptCompiler[0]
      Current runtime is 'win'.
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptProjectProvider[0]
      Creating project file for C:\Users\ashley\Documents\test script\test.csx
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptParser[0]
      Parsing C:\Users\ashley\Documents\test script\test.csx
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptProjectProvider[0]
      Project file saved to C:\Users\ashley\AppData\Local\Temp\scripts\C\Users\ashley\Documents\test script\script.csproj
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptProjectProvider[0]
      <?xml version="1.0" encoding="utf-8"?>
      <Project Sdk="Microsoft.NET.Sdk">
        <PropertyGroup>
          <OutputType>Exe</OutputType>
          <TargetFramework>netcoreapp2.1</TargetFramework>
          <LangVersion>latest</LangVersion>
        </PropertyGroup>
        <ItemGroup></ItemGroup>
      </Project>
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptProjectProvider[0]
      Generating NuGet config evaluated at C:\Users\ashley\Documents\test script to C:\Users\ashley\AppData\Local\Temp\scripts\C\Users\ashley\Documents\test script\NuGet.Config
dbug: Dotnet.Script.DependencyModel.Context.CachedRestorer[0]
      Found cached csproj file at: C:\Users\ashley\AppData\Local\Temp\scripts\C\Users\ashley\Documents\test script\script.csproj.cache
dbug: Dotnet.Script.DependencyModel.Context.CachedRestorer[0]
      Skipping restore. C:\Users\ashley\AppData\Local\Temp\scripts\C\Users\ashley\Documents\test script\script.csproj and C:\Users\ashley\AppData\Local\Temp\scripts\C\Users\ashley\Documents\test script\script.csproj.cache are identical.
dbug: Dotnet.Script.DependencyModel.Context.ProfiledRestorer[0]
      Restoring C:\Users\ashley\AppData\Local\Temp\scripts\C\Users\ashley\Documents\test script\script.csproj took 2ms
dbug: Dotnet.Script.Core.ScriptCompiler[0]
      Configuration/Optimization mode: Debug
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      Executing 'dotnet publish "C:\Users\ashley\AppData\Local\Temp\scripts\C\Users\ashley\Documents\test script\script.csproj" -c Release -r win10-x64 -o C:\Users\ashley\Documents\test script\publish\win10-x64'
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      Microsoft (R) Build Engine version 16.0.450+ga8dc7f1d34 for .NET Core
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      Copyright (C) Microsoft Corporation. All rights reserved.
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      MSBUILD : error MSB1008: Only one project can be specified.
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      Switch: script\publish\win10-x64
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      For switch syntax, type "MSBuild -help"
System.Exception: dotnet publish failed with result '1'
   at Dotnet.Script.Core.ScriptPublisher.CreateExecutable[TReturn,THost](ScriptContext context, LogFactory logFactory, String runtimeIdentifier) in C:\Users\VssAdministrator\AppData\Local\Temp\tmp794B\Dotnet.Script.Core\ScriptPublisher.cs:line 91
   at Dotnet.Script.Core.Commands.PublishCommand.Execute(PublishCommandOptions options) in C:\Users\VssAdministrator\AppData\Local\Temp\tmp794B\Dotnet.Script.Core\Commands\PublishCommand.cs:line 47
   at Dotnet.Script.Program.<>c__DisplayClass4_4.<Wain>b__14() in C:\Users\VssAdministrator\AppData\Local\Temp\tmp794B\Dotnet.Script\Program.cs:line 180
   at Dotnet.Script.Program.Wain(String[] args) in C:\Users\VssAdministrator\AppData\Local\Temp\tmp794B\Dotnet.Script\Program.cs:line 209
   at Dotnet.Script.Program.Main(String[] args) in C:\Users\VssAdministrator\AppData\Local\Temp\tmp794B\Dotnet.Script\Program.cs:line 27
```

**Comment by foresightyj** [comment]
I am still having a similar problem when my folder name is `hello-dotnet-script` but after renaming the folder to `helloDotNetScripts`, the publish command works ok. 

My environment:

```
~/Desktop/helloDotNetScripts $ dotnet --info
.NET SDK (反映任何 global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

运行时环境:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.202\

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  2.1.509 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
```
~/Desktop/helloDotNetScripts $ dotnet script --info
Version             : 1.1.0
Install location    : C:\Users\Administrator\.dotnet\tools\.store\dotnet-script\1.1.0\dotnet-script\1.1.0\tools\net5.0\any
Target framework    : net5.0
.NET Core version   : 5.0.5
Platform identifier : win
Runtime identifier  : win7-x64
```
