### ISSUE TITLE
Cannot publish into executable

### ISSUE THREAD

**Issue by XenoMustache** [filipw/dotnet-script#505]
Running `dotnet script publish main.csx` returns the following:

```
> dotnet script publish main.csx      
dotnet publish failed with result '1'
```

This command had worked before, but for unknown reasons it has stopped working. The script itself is the script generated by the `dotnet script init` command, which is simply to print to the console a "Hello World!" message. 

I've checked permissions of the folder, uninstalled and reinstalled the tool, but nothing has changed.  Further attempts on trying to publish the script have been unsuccessful. It is, however, able to publish into a `.dll` oddly enough, and is able to execute properly as well as a `.dll`.

Other commands, such as `dotnet script main.csx` run successfully, and return the output message.

**Comment by filipw** [comment]
can you post your debug log?

**Comment by XenoMustache** [comment]
Certainly, I was unaware that the program had a debug feature until just now, otherwise I would have posted it with the original issue.

```
System.Exception: Couldn't find file 'public'
   at Dotnet.Script.Core.ScriptFile..ctor(String path) in D:\a\1\s\src\Dotnet.Script.Core\ScriptFile.cs:line 18
   at Dotnet.Script.Program.<>c__DisplayClass4_0.<<Wain>b__9>d.MoveNext() in C:\Users\VssAdministrator\AppData\Local\Temp\tmpCD12\Dotnet.Script\Program.cs:line 213
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 611
   at Dotnet.Script.Program.Wain(String[] args) in C:\Users\VssAdministrator\AppData\Local\Temp\tmpCD12\Dotnet.Script\Program.cs:line 251
   at Dotnet.Script.Program.Main(String[] args) in C:\Users\VssAdministrator\AppData\Local\Temp\tmpCD12\Dotnet.Script\Program.cs:line 27
```

**Comment by XenoMustache** [comment]
My apologies, the above log is incorrect. This is the correct log.
```
info: Dotnet.Script.Core.ScriptCompiler[0]
      Current runtime is 'win'.
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptProjectProvider[0]    
      Creating project file for C:\Users\xenom\Documents\csx\MonoTest\main.csx
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptParser[0]
      Parsing C:\Users\xenom\Documents\csx\MonoTest\main.csx
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptProjectProvider[0]
      Project file saved to C:\Users\xenom\AppData\Local\Temp\scripts\C\Users\xenom\Documents\csx\MonoTest\netcoreapp3.0\script.csproj
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptProjectProvider[0]
      <?xml version="1.0" encoding="utf-8"?>
      <Project Sdk="Microsoft.NET.Sdk">
        <PropertyGroup>
          <OutputType>Exe</OutputType>
          <TargetFramework>netcoreapp3.0</TargetFramework>
          <LangVersion>latest</LangVersion>
        </PropertyGroup>
        <ItemGroup></ItemGroup>
        <Target Name="RecordReferencePaths" AfterTargets="AfterResolveReferences">
          <WriteLinesToFile File="$(OutputPath)/ReferencePaths.txt" Lines="@(ReferencePath)" />
        </Target>
      </Project>
dbug: Dotnet.Script.DependencyModel.Context.CachedRestorer[0]
      Skipping restore. C:\Users\xenom\AppData\Local\Temp\scripts\C\Users\xenom\Documents\csx\MonoTest\netcoreapp3.0\script.csproj and C:\Users\xenom\AppData\Local\Temp\scripts\C\Users\xenom\Documents\csx\MonoTest\netcoreapp3.0\script.csproj.cache are identical.
dbug: Dotnet.Script.DependencyModel.Context.ProfiledRestorer[0]
      Restoring C:\Users\xenom\AppData\Local\Temp\scripts\C\Users\xenom\Documents\csx\MonoTest\netcoreapp3.0\script.csproj took 1ms
dbug: Dotnet.Script.Core.ScriptCompiler[0]
      Configuration/Optimization mode: Debug
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      Executing 'dotnet publish "C:\Users\xenom\AppData\Local\Temp\scripts\C\Users\xenom\Documents\csx\MonoTest\netcoreapp3.0\script.csproj" -c Release -r win10-x64 -o "C:\Users\xenom\Documents\csx\MonoTest\publish\win10-x64"'
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      Microsoft (R) Build Engine version 16.3.2+e481bbf88 for .NET Core
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      Copyright (C) Microsoft Corporation. All rights reserved.
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
        Restore completed in 27.58 ms for C:\Users\xenom\AppData\Local\Temp\scripts\C\Users\xenom\Documents\csx\MonoTest\netcoreapp3.0\script.csproj.
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      C:\Program Files\dotnet\sdk\3.0.101\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3277: Found conflicts between different versions of "Microsoft.CodeAnalysis" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\Users\xenom\AppData\Local\Temp\scripts\C\Users\xenom\Documents\csx\MonoTest\netcoreapp3.0\script.csproj]
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      C:\Program Files\dotnet\sdk\3.0.101\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3277: Found conflicts between different versions of "Microsoft.CodeAnalysis.Scripting" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\Users\xenom\AppData\Local\Temp\scripts\C\Users\xenom\Documents\csx\MonoTest\netcoreapp3.0\script.csproj]
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      C:\Program Files\dotnet\sdk\3.0.101\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3277: Found conflicts between different versions of "System.Buffers" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\Users\xenom\AppData\Local\Temp\scripts\C\Users\xenom\Documents\csx\MonoTest\netcoreapp3.0\script.csproj]
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      obj\Release\netcoreapp3.0\win10-x64\script.AssemblyInfo.cs(10,12): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute [C:\Users\xenom\AppData\Local\Temp\scripts\C\Users\xenom\Documents\csx\MonoTest\netcoreapp3.0\script.csproj]
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      obj\Release\netcoreapp3.0\win10-x64\script.AssemblyInfo.cs(11,12): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute [C:\Users\xenom\AppData\Local\Temp\scripts\C\Users\xenom\Documents\csx\MonoTest\netcoreapp3.0\script.csproj]
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      obj\Release\netcoreapp3.0\win10-x64\script.AssemblyInfo.cs(12,12): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute [C:\Users\xenom\AppData\Local\Temp\scripts\C\Users\xenom\Documents\csx\MonoTest\netcoreapp3.0\script.csproj]
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      obj\Release\netcoreapp3.0\win10-x64\script.AssemblyInfo.cs(13,12): error CS0579: Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute [C:\Users\xenom\AppData\Local\Temp\scripts\C\Users\xenom\Documents\csx\MonoTest\netcoreapp3.0\script.csproj]
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      obj\Release\netcoreapp3.0\win10-x64\script.AssemblyInfo.cs(14,12): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute [C:\Users\xenom\AppData\Local\Temp\scripts\C\Users\xenom\Documents\csx\MonoTest\netcoreapp3.0\script.csproj]
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      obj\Release\netcoreapp3.0\win10-x64\script.AssemblyInfo.cs(15,12): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute [C:\Users\xenom\AppData\Local\Temp\scripts\C\Users\xenom\Documents\csx\MonoTest\netcoreapp3.0\script.csproj]
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      obj\Release\netcoreapp3.0\win10-x64\script.AssemblyInfo.cs(16,12): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute [C:\Users\xenom\AppData\Local\Temp\scripts\C\Users\xenom\Documents\csx\MonoTest\netcoreapp3.0\script.csproj]
System.Exception: dotnet publish failed with result '1'
   at Dotnet.Script.Core.ScriptPublisher.CreateExecutable[TReturn,THost](ScriptContext context, LogFactory logFactory, String runtimeIdentifier) in D:\a\1\s\src\Dotnet.Script.Core\ScriptPublisher.cs:line 94   
   at Dotnet.Script.Core.Commands.PublishCommand.Execute(PublishCommandOptions options) in D:\a\1\s\src\Dotnet.Script.Core\Commands\PublishCommand.cs:line 45
   at Dotnet.Script.Program.<>c__DisplayClass4_4.<Wain>b__14() in C:\Users\VssAdministrator\AppData\Local\Temp\tmpCD12\Dotnet.Script\Program.cs:line 180
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 611
   at Dotnet.Script.Program.Wain(String[] args) in C:\Users\VssAdministrator\AppData\Local\Temp\tmpCD12\Dotnet.Script\Program.cs:line 251
   at Dotnet.Script.Program.Main(String[] args) in C:\Users\VssAdministrator\AppData\Local\Temp\tmpCD12\Dotnet.Script\Program.cs:line 27
```

**Comment by seesharper** [comment]
@XenoMustache Could you do a `dotnet script --info` to dump the environment and also provide a sample script that you are having trouble with?

**Comment by XenoMustache** [comment]
@seesharper Doing so returns nothing. The script I am trying to publish is the sample script included when running `dotnet script init` as stated above.

**Comment by tjorxwrynch** [comment]
I am experiencing the same issue as @XenoMustache.

**Comment by JonLopezGarcia** [comment]
I experienced the same error when trying to publish a script.

I deleted the referenced 'script.AssemblyInfo.cs' file and it worked afterwards.

@XenoMustache this sould be the path of your 'script.AssemblyInfo.cs' file.
`C:\Users\xenom\AppData\Local\Temp\scripts\C\Users\xenom\Documents\csx\MonoTest\netcoreapp3.0\obj\Release\netcoreapp3.0\win10-x64\script.AssemblyInfo.cs`
