### ISSUE TITLE
Could not load Microsoft.CodeAnalysis on script run

### ISSUE THREAD

**Issue by akovalenkousatech** [filipw/dotnet-script#512]
Hello
For some reason I can't run a simple script with "Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'." error.

I'm trying to load the project with Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace and process a set of documents from it.

Got the following output with --debug

> dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptParser[0]
>       Parsing C:\somefolder\someproject\.\codegenerator.csx
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
>  ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load
> a specific file. (0x80131621)
> File name: 'Microsoft.CodeAnalysis, Version=3.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
>  ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
>    at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
>    at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
>    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
>    at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
>    at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
>    at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)
>    at Submission#0.<<Initialize>>d__0.MoveNext()
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
>    at Submission#0.<Initialize>()
>    at Submission#0.<Factory>(Object[] submissionArray)
> 
> 
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Dotnet.Script.Core.ScriptRunner.Execute[TReturn](String dllPath, IEnumerable`1 commandLineArgs) in D:\a\1\s\src\Dotnet.Script.Core\ScriptRunner.cs:line 56
>    at Dotnet.Script.Core.Commands.ExecuteLibraryCommand.Execute[TReturn](ExecuteLibraryCommandOptions options) in D:\a\1\s\src\Dotnet.Script.Core\Commands\ExecuteLibraryCommand.cs:line 30
>    at Dotnet.Script.Core.Commands.ExecuteScriptCommand.ExecuteLibrary[TReturn](String pathToLibrary, String[] arguments, Boolean noCache) in D:\a\1\s\src\Dotnet.Script.Core\Commands\ExecuteScriptCommand.cs:line 138
>    at Dotnet.Script.Core.Commands.ExecuteScriptCommand.Run[TReturn,THost](ExecuteScriptCommandOptions options) in D:\a\1\s\src\Dotnet.Script.Core\Commands\ExecuteScriptCommand.cs:line 35
>    at Dotnet.Script.Program.<>c__DisplayClass4_0.<<Wain>b__9>d.MoveNext() in C:\Users\VssAdministrator\AppData\Local\Temp\tmpCD12\Dotnet.Script\Program.cs:line 242
> --- End of stack trace from previous location where exception was thrown ---
>    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
>    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 611
>    at Dotnet.Script.Program.Wain(String[] args) in C:\Users\VssAdministrator\AppData\Local\Temp\tmpCD12\Dotnet.Script\Program.cs:line 251
>    at Dotnet.Script.Program.Main(String[] args) in C:\Users\VssAdministrator\AppData\Local\Temp\tmpCD12\Dotnet.Script\Program.cs:line 27
> 

You can try it with this repo https://github.com/akovalenkousatech/dotnetscripttest
Just run `dotnet tool restore` and `dotnet script .\codegenerator.csx`

If I lower the version of Microsoft.CodeAnalysis.Workspaces.MCBuild package to 3.0.0, get a lot of errors like this
> System.TypeLoadException: Method 'Equals' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationArrayTypeSymbol' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.

**Comment by hrumhurum** [comment]
It seems that there is an already loaded assembly with the same name `Microsoft.CodeAnalysis` but with different version.

The current implementation does not use `AssemblyLoadContext` functionality of .NET, so the script is not isolated from the host assembly and may be spoiled by the already loaded assemblies.
