### ISSUE TITLE
Using programmatically with single-file publish

### ISSUE THREAD

**Issue by andersstorhaug** [filipw/dotnet-script#610]
I've been using `Dotnet.Script.DependencyModel.NuGet` to support scripting in a host application with NuGet package support.

This works well, unless I publish with `net5.0` and `/p:PublishSingleFile=true`:

```
System.AggregateException: One or more errors occurred. (CodeBase is not supported on assemblies loaded from a single-file bundle.)
 ---> System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.
   at System.Reflection.RuntimeAssembly.get_CodeBase()
   at Dotnet.Script.DependencyModel.Environment.ScriptEnvironment.GetNetCoreVersion()
   at Dotnet.Script.DependencyModel.Environment.ScriptEnvironment.GetNetCoreAppVersion()
```

The exception is self-explanatory, with the offenders being [`GetNetCoreAppVersion`](https://github.com/filipw/dotnet-script/blob/1.0.1/src/Dotnet.Script.DependencyModel/Environment/ScriptEnvironment.cs#L75) and [`GetNetCoreVersion`](https://github.com/filipw/dotnet-script/blob/1.0.1/src/Dotnet.Script.DependencyModel/Environment/ScriptEnvironment.cs#L92).

What I'm wondering is: **could this be corrected by usage of `System.Environment.Version` and/or `System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription`?**

Below is a relevant code snippet which adds NuGet dependencies to an otherwise standard usage of `Microsoft.CodeAnalysis.CSharp.Scripting`.

```c#
var scriptOptions = ScriptOptions.Default
        .WithFilePath(_path)
        .AddImports(
            "System",
            "System.IO",
            "System.Collections.Generic",
            "System.Console",
            "System.Diagnostics",
            "System.Linq",
            "System.Text",
            "System.Threading.Tasks");

if (_useNuget)
{
    var references = DependencyResolver
        .GetDependencies(_path, packageSources: Array.Empty<string>())
        .SelectMany(dependency => dependency.Assemblies)
        .Distinct()
        .GroupBy(assembly => assembly.Name.FullName)
        .Select(assemblies => assemblies.OrderBy(assembly => assembly.Name.Version).Last())
        .Select(assembly => MetadataReference.CreateFromFile(assembly.Path));

    scriptOptions = scriptOptions
        .AddReferences(references)
        .WithLanguageVersion(LanguageVersion.Preview)
        .WithFileEncoding(Encoding.UTF8)
        .WithMetadataResolver(new NuGetMetadataReferenceResolver(ScriptMetadataResolver.Default));
}

var script = CSharpScript.Create<TReturn>(code: File.ReadAllText(_path), scriptOptions);
var diagnostics = script.Compile();
```

---

Side note: I use `dotnet script` all the time for quick C# spikes, and of course also this use-case now in a couple of applications. Great project :+1:.

**Comment by andersstorhaug** [comment]
Ok, so, I have been playing around with this and determined that I can use the `NuGet.Commands NuGet package to restore and reference packages.

See this [gist](https://gist.github.com/andersstorhaug/c7460c7e754f343ae1ad2c6fd8dba051).

I'm not sure if this is useful, and it may need more work, but I think it will allow me to use Roslyn scripting with NuGet support without requiring an installed .NET SDK.

**Comment by andersstorhaug** [comment]
See also https://github.com/dotnet/roslyn/issues/50719 for issues with `MetadataReference` and .NET 5 single-file publish.
