### ISSUE TITLE
FileLoadException when running C# script

### ISSUE THREAD

**Issue by badclone** [filipw/dotnet-script#613]
I wrote the following C# script (HelloWorld.csx file):

```
#! "netcoreapp3.1"
#r "nuget: System.Text.Encoding.CodePages, 5.0.0"

public class Script
{
    public static void Run()
    {
        try
        {
            System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
        }
        catch (Exception ex)
        {
            System.Console.WriteLine(ex.ToString());
        }
    }
}

Script.Run();
```

I'm using dotnet-script (version 1.0.1) and .NET Runtime (version 3.1.14)

When executing this script, I get the following error. Any idea why?

`dotnet script HelloWorld.csx`

> System.IO.FileLoadException: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
> File name: 'System.Text.Encoding.CodePages, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
>  ---> System.IO.FileLoadException: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
>    at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
>    at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
>    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
>    at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
>    at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
>    at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)
>    at Submission#0.Script.Run()
>    at Submission#0.<<Initialize>>d__0.MoveNext() in D:\scripts\HelloWorld.csx:line 18
> --- End of stack trace from previous location where exception was thrown ---
>    at Dotnet.Script.Core.ScriptRunner.Execute[TReturn](String dllPath, IEnumerable`1 commandLineArgs) in /private/var/folders/6j/4hkjjhd50fg27s933nctz0480000gn/T/tmp3iI6tV/Dotnet.Script.Core/ScriptRunner.cs:line 52

**Comment by filipw** [comment]
dotnet-script preloads version `4.7.1` of `System.Text.Encoding.CodePages` due to an old workaround which means a newer major cannot be resolved. 

Did you try with that version?

**Comment by badclone** [comment]
Yep, if I use version 4.7.0 in my example, it works.

However, this example is a bit different from my real production script. In my real script, I need to use a NuGet package (which targets .NET Standard 2.0) that has a dependency on System.Text.Encoding.CodePages version 5.0.0 and I don't have control on that.

```
MyScript.csx
    └--> NuGet Package A (.NET Standard 2.0)
                 └--> System.Text.Encoding.CodePages (version 5.0.0)
```

Is there a way to "force" to use the version 4.7.0?

I tried this, but I get a package downgrade error:
```
MyScript.csx
    └--> NuGet Package A (.NET Standard 2.0)
                 └--> System.Text.Encoding.CodePages (version 5.0.0)
    └--> System.Text.Encoding.CodePages (version 4.7.0)
```

> error NU1605: Detected package downgrade: System.Text.Encoding.CodePages from 5.0.0 to 4.7.0

**Comment by badclone** [comment]
`dotnet script --info`

> Version             : 1.0.1
> Install location    : C:\Users\fchartrand\.dotnet\tools\.store\dotnet-script\1.0.1\dotnet-script\1.0.1\tools\netcoreapp3.1\any
> Target framework    : netcoreapp3.1
> .NET Core version   : 3.1.14
> Platform identifier : win
> Runtime identifier  : win10-x64

**Comment by seesharper** [comment]
Thanks. We are falling behind on several dependencies that now have been released in 5.x.x versions. I'll bump the deps and verify that all tests still passes. 👍

**Comment by seesharper** [comment]
Fixed by #614
