### ISSUE TITLE
Errors, Fails to reference System.Reactive

### ISSUE THREAD

**Issue by dave-yotta** [filipw/dotnet-script#625]
I had this runtime dll not found problem when referencing one of our packages that uses System.Reactive, I'll show at end.  I tried a simple repro script and found it's not resolving System.Reactive at all for some reason:
```
root@docker-desktop:~/testy# cat main.csx
#! "netcoreapp3.1"
#r "nuget: System.Reactive, 5.0"
using System.Reactive.Disposables;

var davv = new RefCountDisposable(null);
root@docker-desktop:~/testy# dotnet script main.csx
warn: Dotnet.Script.Core.Commands.ExecuteScriptCommand[0]
      The script /root/testy/main.csx is not cacheable. For caching and optimal performance, ensure that the script only contains NuGet references with pinned/exact versions.
warn: Dotnet.Script.DependencyModel.Context.CachedRestorer[0]
      Unable to cache /root/.cache/dotnet-script/root/testy/netcoreapp3.1/script.csproj. For caching and optimal performance, ensure that the script(s) references Nuget packages with a pinned version.
/root/testy/main.csx(3,14): error CS0234: The type or namespace name 'Reactive' does not exist in the namespace 'System' (are you missing an assembly reference?)
/root/testy/main.csx(5,16): error CS0246: The type or namespace name 'RefCountDisposable' could not be found (are you missing a using directive or an assembly reference?)
```

Not sure why it thinks it's not cacheable either - System.Reactive has no netcoreapp3.1 dependencies - perhaps its picking .net standard, those are >= conditions. Original runtime error I got, same thing just late bound.
```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Reactive, Version=5.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. The system cannot find the file specified.

File name: 'System.Reactive, Version=5.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'
   at AlloyEngine.EngineApis.EngineCode.Workflows.VirtualParameters.Scripting.Services.Implementations.AlloyWorkflowsDaemon.AlloyDaemonCacheValue..ctor(AlloyWorkflowsDaemon daemon)
   at AlloyEngine.EngineApis.EngineCode.Workflows.VirtualParameters.Scripting.Services.Implementations.AlloyWorkflowsDaemon.AlloyDaemonCacheEntry.StartNewDaemon(String pathToDaemonExecutable, String daemonUser, String daemonUserPassword)
   at AlloyEngine.EngineApis.EngineCode.Workflows.VirtualParameters.Scripting.Services.Implementations.AlloyWorkflowsDaemon.AlloyDaemonCacheEntry.TryGetDaemonReference()
   at AlloyEngine.EngineApis.EngineCode.Workflows.VirtualParameters.Scripting.Services.Implementations.AlloyWorkflowsDaemon.AlloyWorkflowsDaemonFactory.GetOrCreate()
   at AlloyEngine.EngineApis.EngineCode.Workflows.VirtualParameters.WorkflowVirtualParameterElementScript.GetNeeds()
   at AlloyEngine.EngineApis.EngineCode.Workflows.VirtualParameters.WorkflowParameterEvaluator.GetNodeNeeds[T](Dictionary`2 elements)
   at AlloyEngine.EngineApis.EngineCode.Workflows.VirtualParameters.WorkflowParameterEvaluator.Resolve()
   at AlloyEngine.EngineApis.EngineCode.Workflows.WorkflowNodeHelper.GetActionConfiguration(IActionNode action, WorkflowContextChainBase input, Boolean isFinal)
   at AlloyEngine.EngineApis.EngineCode.Workflows.WorkflowNodeHelper.ComputeOutputChainOfNode(AId nodeId)
   at AlloyEngine.EngineApis.EngineCode.Workflows.WorkflowNodeValidator.ValidateActionParameters(IActionNode action, ISet`1 attributesToIgnore)
   at AlloyEngine.EngineApis.EngineApi.AddWorkflowAction(AddWorkflowActionRequest model)
   at Submission#0.<Quick>d__10.MoveNext() in /local/stress-test/workflow-script-fastslow/main.csx:line 43
--- End of stack trace from previous location where exception was thrown ---
   at Submission#0.<<Initialize>>d__0.MoveNext() in /local/stress-test/workflow-script-fastslow/main.csx:line 36
--- End of stack trace from previous location where exception was thrown ---
   at Dotnet.Script.Core.ScriptRunner.Execute[TReturn](String dllPath, IEnumerable`1 commandLineArgs) in C:\Users\VssAdministrator\AppData\Local\Temp\tmp5FE3\Dotnet.Script.Core\ScriptRunner.cs:line 52
   ```

**Comment by dave-yotta** [comment]
Here u go:
```
root@docker-desktop:~/tt# dotnet script --info
Version             : 1.1.0
Install location    : /root/.dotnet/tools/.store/dotnet-script/1.1.0/dotnet-script/1.1.0/tools/netcoreapp3.1/any
Target framework    : netcoreapp3.1
.NET Core version   : 3.1.15
Platform identifier : linux
Runtime identifier  : linux-x64
```

that's on docker...get it on my host too for v0.53 I had installed on there, but worked for 1.1.0:
```
S C:\Users\d_hig\source\yotta\tt> dotnet script --info
Version             : 0.53.0
Install location    : C:\Users\d_hig\.dotnet\tools\.store\dotnet-script\0.53.0\dotnet-script\0.53.0\tools\netcoreapp3.1\any
Target framework    : netcoreapp3.1
.NET Core version   : 3.1.13
Platform identifier : win
Runtime identifier  : win10-x64
Version 1.1.0 is now available
Depending on how dotnet-script was installed, execute on of the following commands to update.
Global tool : dotnet tool update dotnet-script -g
Chocolatey  : choco upgrade Dotnet.Script
Powershell  : (new-object Net.WebClient).DownloadString("https://raw.githubusercontent.com/filipw/dotnet-script/master/install/install.ps") | iex
PS C:\Users\d_hig\source\yotta\tt> dotnet tool update dotnet-script -g
Tool 'dotnet-script' was successfully updated from version '0.53.0' to version '1.1.0'.
```

**Comment by filipw** [comment]
Is the System.Reactive 5.0 expected to work with .NET Core 3.1? You could update the .NET SDK to .NET 5 and then it should definitely work fine.

**Comment by dave-yotta** [comment]
Yeah check the nuget page:

![image](https://user-images.githubusercontent.com/41444963/121014056-77dba200-c791-11eb-893a-26e3d6fb8690.png)

We're using it in our .net core 3.1 application without issue.

**Comment by dave-yotta** [comment]
Hey any update on this? What I'm saying in my last comment there is that System.Reactive supports .netcore3.1 as listed there.  Works in a normal csproj, just not in .net script.

I see that it restores system.reactive to the packages directory - but this guy when .net script runs: `trce: Dotnet.Script.Core.ScriptCompiler[0]      Adding reference to a runtime dependency =>` never adds System.Reactive.

Checking the `script.csproj` that resolvereferences is done on, I get this output after build, with the system.reactive having a strange transitive path:

(just a bit of the output of `root@docker-desktop:~/.cache/dotnet-script/dt/netcoreapp3.1# dotnet build script.csproj /p:OutputType=Library`)
```
...
/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.ObjectModel.dll
/root/.nuget/packages/system.reactive/5.0.0/buildTransitive/netcoreapp3.1/../../lib/netstandard2.0/System.Reactive.dll
/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Reflection.DispatchProxy.dll
/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Reflection.dll
/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Reflection.Emit.dll
...
```
But now I look at the code, it's here https://github.com/filipw/dotnet-script/blob/master/src/Dotnet.Script.DependencyModel/Context/ScriptDependencyContextReader.cs#L37, reading the lock file that creates dependencies for libraries on a `dotnet script my.csx` call.

![image](https://user-images.githubusercontent.com/41444963/135656583-9adc43c6-388b-4cb4-b712-43f730ceebfe.png)

Debugged above it on WSL - this only happens on linux.

The package has a file `    "lib/netcoreapp3.1/_._",` which is skipped in `GetRuntimeDependencyPaths`.  Tried to let it load it but it gets `Could not load file or assembly '/home/flavourous/.nuget/packages/system.reactive/5.0.0/lib/netcoreapp3.1/_._'. An attempt was made to load a program with an incorrect format.`.

Don't really know what's going on here - but using System.Reactive (5.0) in a normal csproj targetting netcoreapp3.1 compiles and runs without any error, so there's got to be some semantic to do with transitive references being missed here.

**Comment by seesharper** [comment]
Tried this on my Mac. No Problem. On Ubuntu 18.04 it fails as described by @dave-yotta
