### ISSUE TITLE
Debugging scripts loaded in via #load directive

### ISSUE THREAD

**Issue by Sharpiro** [filipw/dotnet-script#74]
I no longer have access to older versions of dotnet that use project.json so i modified your source to just ignore the part where it checks for it so that I could use just a .csx file w/ no project.json/csproj and got the debugging working w/ c#7.  You can see that change [here](https://github.com/filipw/dotnet-script/compare/master...Sharpiro:feature/testing#diff-f6017048243d1ae78f5d0973d541aa31)

So my issue is that if load in another script from the main debuggable script via ```#load```, I get the following issue when setting a breakpoint in that loaded in script:
```
WARNING: Could not load symbols for 'ℛ*c9b5c793-2995-47ba-9ae3-b0c8d54c3bdf#1-0'. 'C:\Program Files\dotnet\ℛ*c9b5c793-2995-47ba-9ae3-b0c8d54c3bdf#1-0.pdb' could not be opened.
Loaded 'ℛ*c9b5c793-2995-47ba-9ae3-b0c8d54c3bdf#1-0'. Cannot find or open the PDB file.
Breakpoint warning: The source code is different from the original version.
To allow this breakpoint to be hit: Add '"requireExactSource": false' to launch.json and restart debugging. - c:\temp\gen\Other.csx:4
```

I tried setting the ```requireExactSource```  to false, but it didn't help.

I can't confirm, but I would guess that your dotnet-script using project.json would have this issue to.  Any idea on what would be necessary for that other script to have accurate PDB information loaded as well?

**Comment by filipw** [comment]
Should be fixed with #75 

<img width="1154" alt="screenshot 2017-03-27 08 56 22" src="https://cloud.githubusercontent.com/assets/1710369/24344541/49ed3b2a-12cc-11e7-9bd2-5b217b6d2f38.png">

**Comment by Sharpiro** [comment]
Do you have the code you took a screenshot of available for download?  I tried the latest version with PR 75, but I still could not get the breakpoint to be hit.

**Comment by filipw** [comment]
note that you will still need `requireExactSource: false` there

**Comment by Sharpiro** [comment]
Ahh, yes that did allow breakpoints to be hit.  Though they don't always hit exactly where placed.  Thank you.

**Comment by filipw** [comment]
Things should also get better once this change gets out (Roslyn 2.1 / Roslyn 3) https://github.com/dotnet/roslyn/pull/16489

**Comment by seesharper** [comment]
FYI the current implementation sometimes causes an exception when trying to emit debug symbols.
I ran this against some existing scripts i had and it rather randomly throws this exception.

```
   at Microsoft.CodeAnalysis.Text.SourceText.LineInfo.IndexOf(Int32 position)
   at Microsoft.CodeAnalysis.Text.SourceText.LineInfo.GetLineFromPosition(Int32 position)
   at Microsoft.CodeAnalysis.Text.TextLineCollection.GetLinePosition(Int32 position)
   at Microsoft.CodeAnalysis.CSharp.Syntax.CSharpLineDirectiveMap.TranslateSpanAndVisibility(SourceText sourceText, String treeFilePath, TextSpan span, Boolean& isHiddenPosition)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.GetMappedLineSpanAndVisibility(TextSpan span, Boolean& isHiddenPosition)
   at Microsoft.CodeAnalysis.CodeGen.SequencePointList.GetSequencePoints(DebugDocumentProvider documentProvider, ArrayBuilder`1 builder)
   at Microsoft.Cci.MetadataWriter.SerializeMethodDebugInfo(IMethodBody bodyOpt, Int32 methodRid, StandaloneSignatureHandle localSignatureHandleOpt, LocalVariableHandle& lastLocalVariableHandle, LocalConstantHandle& lastLocalConstantHandle)
   at Microsoft.Cci.MetadataWriter.SerializeMethodBodies(BlobBuilder ilBuilder, PdbWriter nativePdbWriterOpt, Blob& mvidStringFixup)
   at Microsoft.Cci.MetadataWriter.BuildMetadataAndIL(PdbWriter nativePdbWriterOpt, BlobBuilder ilBuilder, BlobBuilder mappedFieldDataBuilder, BlobBuilder managedResourceDataBuilder, Blob& mvidFixup, Blob& mvidStringFixup)
   at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean allowMissingMethodBodies, Boolean isDeterministic, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, Func`1 testSymWriterFactory, DiagnosticBag diagnostics, Boolean metadataOnly, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, CompilationTestData testData, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, CancellationToken cancellationToken)
   at Dotnet.Script.Core.DebugScriptRunner.Execute[TReturn,THost](ScriptContext context, THost host)
   at Dotnet.Script.Core.ScriptRunner.Execute[TReturn](ScriptContext context)
   at Dotnet.Script.Program.Run(Boolean debugMode, ScriptContext context)
   at Dotnet.Script.Program.RunScript(String file, String config, Boolean debugMode, IEnumerable`1 args)
   at Dotnet.Script.Program.<>c__DisplayClass3_1.<Wain>b__2()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Dotnet.Script.Program.Wain(String[] args)
   at Dotnet.Script.Program.Main(String[] args)
```

This happens only for the scripts loaded through the #load directive and I have spent all day trying to figure out a way around this. First it looked like it was related to comments in the script, but I later on ran into the same issue with a #load(ed) script without comments. Finally gave up on the issue and moved to the nightly build of Roslyn where your PR is included. I then worked as expected without all these crazy reflection hacks. Good job BTW. 

Thought I would let you know just in case you encounter this.

**Comment by filipw** [comment]
great, i was actually thinking of moving this to latest Roslyn nightlies, this might be the last straw

**Comment by Sharpiro** [comment]
Not trying to be a buzz-kill, but just FYI:

I moved my dotnet-script branch which is up to date w/ master over to Roslyn nightlies, and it did not improve breakpoint accuracy, and ```requireExactSource: false``` property was still required for any breakpoint to be hit at all in the ```#load```ed script.

**Comment by filipw** [comment]
did you update to use the new script debugging API?

**Comment by seesharper** [comment]
That is probably because most of the stuff you see in the DebugScriptRunner is actually not needed anymore as you can simply do this now
```
 scriptOptions = scriptOptions.WithEmitDebugInformation(true);
```

and then simply execute the script. We don't need to "manually" emit the symbols ourself. 
The lack of accuracy is probably related to what I mentioned about sometimes an exception was thrown when emitting symbols.

**Comment by Sharpiro** [comment]
I did not actually make those other changes, if you don't already update your branch with the nightlies + those changes, i'll give it a try and report back my findings when I have some time.

**Comment by Sharpiro** [comment]
So I was able to make the changes you guys reccomended, and it does indeed work better, but not perfectly.

You can see my changes from the current master [here](https://github.com/filipw/dotnet-script/compare/master...Sharpiro:feature/testing)

So when running from VS, I have to ```#load``` the fully qualified name of the other script.  It hits the breakpoint on the "bar.csx", but then fails to return to the original "foo.csx" script.

When running from VS Code, I get a better experience, but 1 odd thing happens.  If i set a breakpoint on line 4 and 6 of "foo.csx" and line 3 and 5 of "bar.csx", the order of breakpoints hit is bar-5, foo-4, foo-6, and then bar-3.  This may be an issue with the ```LocalDeclarationStatementSyntax ```, because if I change bar-3 to just a ```Console.WriteLine("test");``` then the breakpoints will proceed in an accurate order.

Aslo note that with VS Code I was able to set ``` "requireExactSource": true```, though it doesn't seem to make any difference in outcome.

All in all much better experience so far!  Thanks.
